import os
import openai
import streamlit as st

openai.api_key = ("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")

def generate_images():
  images = openai.Image.create(
  prompt="Motorola walkie talkie illustration in the style of Hayao Miyazaki",
  n=5,
  size="1024x1024"
  )
  return images

st.title("Motorola Walkie Talkie Illustrations")

images = generate_images()
for image in images:
  st.image(image, width=600)

st.info("Generated by OpenAI")
