import os
import openai
import streamlit as st

openai.api_key = ("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")

def generate_images():
images = openai.Image.create(
prompt="Motorola walkie talkie illustration in the style of Hayao Miyazaki",
n=5,
size="1024x1024"
)

return images

st.title("Motorola Walkie Talkie Illustrations")

images = generate_images()
for image in images:
st.image(image, width=600)

st.info("Generated by OpenAI")